apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: svetlinvatev/kub-demo-tasks:latest
        env:
        - name: AUTH_ADDRESS
          # value: "10.99.66.243"
          value: "auth-service.default"
        - name: TASKS_FOLDER
          value: tasks